'use client'
import { Children } from 'react';
import '../styles/globals.css';
import Nav from '../components/Nav';
import Footer from '../components/Footer';
import { AuthContextProvider } from '../context/AuthContext';

export const metadata = {
  title: 'Mystore',
  description: 'Generated by create next app',
}

const RootLayout = ({children}) => {
  return (
    <html lang="en">
      <body>  
        <main> 
          <AuthContextProvider>
            <Nav />
        {children}
        <Footer />
          </AuthContextProvider>
        
        </main> 
      </body>
      
    </html>
   
  )
}

export default RootLayout